spring:
  application:
    name: challengeaccepted
  jpa:
    properties:
      dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:sqlserver://challengeaccepted.database.windows.net:1433/challengeaccepted
    username: himymb@challengeaccepted
    password: Bananbanan666
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  context-path: /api

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    com.challengeaccepted: INFO