spring:
  application:
    name: challengeaccepted
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
    hibernate:
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:sqlserver://challengeaccepted.database.windows.net:1433;database=challengeaccepted;user=himymb@challengeaccepted;password=Bananbanan666;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: himymb
    password: Bananbanan666
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  context-path: /api

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    com.challengeaccepted: INFO